//problem1
SELECT CITY , STATE FROM STATION;
//problem2
SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0;
//problem3
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California';
//problem4
SELECT COUNT(ID) FROM CITY WHERE POPULATION > 100000;
//problem5
//cannot solve it