//problem1
SELECT NAME FROM EMPLOYEE WHERE MONTHS < 10 AND SALARY > 2000 ORDER BY EMPLOYEE_ID ASC;
//problem2
SELECT name FROM city WHERE countrycode IN (SELECT CODE FROM COUNTRY WHERE CONTINENT = 'AFRICA');
//problem3
SELECT SUM (POPULATION) FROM CITY WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY WHERE CONTINENT = 'Asia');
//problem4
UPDATE Salary SET SEX = CASE WHEN SEX = 'f' THEN 'm' ELSE 'f' END;
//problem5
SELECT S.NAME FROM STUDENTS AS S 
JOIN FRIENDS AS F ON S.ID = F.ID 
JOIN PACKAGES AS P1 ON S.ID = P1.ID
JOIN PACKAGES AS P2 ON F.FRIEND_ID = P2.IDWHERE P2.SALARY > P1.SALARY
ORDER BY P2.SALARY; 