//problem 1
SELECT * FROM CITY;
  //problem2
  SELECT * FROM CITY
WHERE ID = 1661;
  //problem 3
  SELECT * FROM CITY
WHERE POPULATION > 100000 AND
COUNTRYCODE = 'USA';
  //problem 4
  SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'JPN';
